apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: agentic-architect
build:
  local:
    push: false
  artifacts:
    - image: agentic-architect
      context: .
      docker:
        dockerfile: apps/architect/Dockerfile
      sync:
        manual:
          - src: "apps/architect/**/*.py"
            dest: .
    - image: custom-ollama-gemma
      context: .
      docker:
        dockerfile: infra/Ollama.Dockerfile

deploy:
  helm:
    releases:
      - name: the-architect
        chartPath: infra/charts/the-architect
        valuesFiles:
          - infra/charts/the-architect/values.yaml
        setValueTemplates:
          ollama.image: "{{.IMAGE_FULLY_QUALIFIED_custom_ollama_gemma}}"
          architect.image: "{{.IMAGE_FULLY_QUALIFIED_agentic_architect}}"


portForward:
  # NiceGUI
  - resourceType: service
    resourceName: architect-service
    namespace: agentic-architect
    port: 8080
    localPort: 8080
  # Observability
  - resourceType: service
    resourceName: phoenix
    namespace: agentic-architect
    port: 6006
    localPort: 6006
  # Remote dev (Interactive)
  - resourceType: service
    resourceName: architect-service
    port: 2718
    localPort: 2718