# Default Configuration
namespace: agentic-architect

global:
  imagePullPolicy: IfNotPresent

ollama:
  image: custom-ollama-gemma
  cpu: "1"
  memory: "2Gi"

arangodb:
  image: arangodb/arangodb:3.11
  storageSize: "2Gi"

architect:
  image: agentic-architect
  env: "test"
  cpu: "0.5"
  memory: "1Gi"

phoenix:
  image: arizephoenix/phoenix:latest

ingress:
  enabled: false