ingress:
  enabled: true
  host: "thearchitect.dev"
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
  tls:
    - hosts:
        - thearchitect.dev