name: CICD-Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Free Disk Space (Cleanup)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/node_modules
          sudo docker image prune -af
          df -h

      - name: Install Devbox
        uses: jetpack-io/devbox-install-action@v0.11.0

      - name: Setup Infrastructure (Devbox + K3D)
        run: devbox run set

      - name: Build and Deploy with Skaffold
        run: devbox run skaffold run

      - name: Run Integration Tests
        run: devbox run test-ci

      - name: Deploy Infrastructure & App
        if: github.ref == 'refs/heads/main' && success()
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          OVH_ENDPOINT: ${{ secrets.OVH_ENDPOINT }}
          OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
          OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
        run: |
          devbox run pulumi config set --secret kubeconfig "${{ secrets.KUBECONFIG_VPS }}" -C infra
          devbox run infra-up

      - name: Debug on Failure
        if: failure()
        run: devbox run debug-ci